# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
  boot.loader.systemd-boot.enable = true;

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/858866af-4f48-4d63-8782-da5bad8d96c7";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/282A-C534";
      fsType = "vfat";
    };

  fileSystems."/media" =
    {
      device = "/dev/disk/by-uuid/DA80038C80036E77";
      fsType = "ntfs";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/b21a2391-9889-4ccf-a663-e81a422b139f"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.nvidia.modesetting.enable = true;
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.beta;
  hardware.nvidia.open = false;
  hardware.graphics = {
    enable = true;
  };
  services.xserver.videoDrivers = [ "nvidia" ];

  networking.hostName = "krypton"; # Define your hostname.
  networking.wireless.enable = false; # Enables wireless support via wpa_supplicant.
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp0s31f6.useDHCP = true;
}
